### ISSUE TITLE
How to debug

### ISSUE THREAD

**Issue by dbeulen** [jwinarske/meta-vulkan#11]
I am currently trying to get swiftshader vulkan implementation working on a imx7 (without GPU). In the end I am are trying to run flutter : [https://github.com/meta-flutter/meta-flutter/issues/26](https://github.com/meta-flutter/meta-flutter/issues/26)

However when i add swiftshader and sasha samples on a build with wayland support the examples dont run correctly. The samples do find the swiftshader vulkan implementation, but when they are started only a black (or with some samples blue) background appears. The color does seem to come from the sample implementation. 

As i suspected the problem might be in the wayland connection, i tried to compile the software with directfb support, but unfortunately i could not compile this. (See [issue](https://github.com/jwinarske/meta-vulkan/issues/10))

At this point a actually do not know what to do any further. How can i test the swiftshader and samples so I can find out where it goes wrong?

**Comment by jwinarske** [comment]
This layer is tricky to get setup correctly.  The dunfell-no-mesa uses mesa as-is.  For RaspberryPi4 using latest Mesa Vulkan support (required), the `dunfell` branch works.  For Other targets that don't require more recent Mesa, or Mesa at all `dunfell-no-mesa` should work.  What branch are you using?

**Comment by jwinarske** [comment]
closing due to lack of response
